spring:
  application:
    name: dubbo-spring-provider
  profiles:
    active: dev


dubbo:
  scan:
    base-packages: com.atomscat
  registry:
    address: 192.168.31.165:2181,192.168.31.165:2182,192.168.31.165:2183
    protocol: zookeeper
  protocol:
    port: 28038

#内嵌服务器端口
server:
  port: 8080
